In [20]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.preprocessing.sequence import pad_sequences

In [22]:
# Sample text data
text = "The quick brown fox jumps over the lazy dog. "
chars = sorted(list(set(text)))
char_to_int = {c:i for i,c in enumerate(chars)}

In [24]:
# Prepare dataset
seq_length = 10
X = []; y = []
for i in range(len(text) - seq_length):
    seq_in = text[i:i + seq_length]
    seq_out = text[i + seq_length]
    X.append([char_to_int[char] for char in seq_in])
    y.append(char_to_int[seq_out])

In [30]:
# Build model
model = Sequential([
    Embedding(len(chars), 50),
    LSTM(100, return_sequences=True),
    LSTM(100),
    Dense(len(chars), activation='softmax')
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

In [32]:
# Train model
model.fit(tf.expand_dims(X, -1), y, epochs=100, batch_size=32)

ValueError: Unrecognized data type: x=[[[ 2]
  [10]
  [ 7]
  [ 0]
  [19]
  [23]
  [11]
  [ 5]
  [13]
  [ 0]]

 [[10]
  [ 7]
  [ 0]
  [19]
  [23]
  [11]
  [ 5]
  [13]
  [ 0]
  [ 4]]

 [[ 7]
  [ 0]
  [19]
  [23]
  [11]
  [ 5]
  [13]
  [ 0]
  [ 4]
  [20]]

 [[ 0]
  [19]
  [23]
  [11]
  [ 5]
  [13]
  [ 0]
  [ 4]
  [20]
  [17]]

 [[19]
  [23]
  [11]
  [ 5]
  [13]
  [ 0]
  [ 4]
  [20]
  [17]
  [25]]

 [[23]
  [11]
  [ 5]
  [13]
  [ 0]
  [ 4]
  [20]
  [17]
  [25]
  [16]]

 [[11]
  [ 5]
  [13]
  [ 0]
  [ 4]
  [20]
  [17]
  [25]
  [16]
  [ 0]]

 [[ 5]
  [13]
  [ 0]
  [ 4]
  [20]
  [17]
  [25]
  [16]
  [ 0]
  [ 8]]

 [[13]
  [ 0]
  [ 4]
  [20]
  [17]
  [25]
  [16]
  [ 0]
  [ 8]
  [17]]

 [[ 0]
  [ 4]
  [20]
  [17]
  [25]
  [16]
  [ 0]
  [ 8]
  [17]
  [26]]

 [[ 4]
  [20]
  [17]
  [25]
  [16]
  [ 0]
  [ 8]
  [17]
  [26]
  [ 0]]

 [[20]
  [17]
  [25]
  [16]
  [ 0]
  [ 8]
  [17]
  [26]
  [ 0]
  [12]]

 [[17]
  [25]
  [16]
  [ 0]
  [ 8]
  [17]
  [26]
  [ 0]
  [12]
  [23]]

 [[25]
  [16]
  [ 0]
  [ 8]
  [17]
  [26]
  [ 0]
  [12]
  [23]
  [15]]

 [[16]
  [ 0]
  [ 8]
  [17]
  [26]
  [ 0]
  [12]
  [23]
  [15]
  [18]]

 [[ 0]
  [ 8]
  [17]
  [26]
  [ 0]
  [12]
  [23]
  [15]
  [18]
  [21]]

 [[ 8]
  [17]
  [26]
  [ 0]
  [12]
  [23]
  [15]
  [18]
  [21]
  [ 0]]

 [[17]
  [26]
  [ 0]
  [12]
  [23]
  [15]
  [18]
  [21]
  [ 0]
  [17]]

 [[26]
  [ 0]
  [12]
  [23]
  [15]
  [18]
  [21]
  [ 0]
  [17]
  [24]]

 [[ 0]
  [12]
  [23]
  [15]
  [18]
  [21]
  [ 0]
  [17]
  [24]
  [ 7]]

 [[12]
  [23]
  [15]
  [18]
  [21]
  [ 0]
  [17]
  [24]
  [ 7]
  [20]]

 [[23]
  [15]
  [18]
  [21]
  [ 0]
  [17]
  [24]
  [ 7]
  [20]
  [ 0]]

 [[15]
  [18]
  [21]
  [ 0]
  [17]
  [24]
  [ 7]
  [20]
  [ 0]
  [22]]

 [[18]
  [21]
  [ 0]
  [17]
  [24]
  [ 7]
  [20]
  [ 0]
  [22]
  [10]]

 [[21]
  [ 0]
  [17]
  [24]
  [ 7]
  [20]
  [ 0]
  [22]
  [10]
  [ 7]]

 [[ 0]
  [17]
  [24]
  [ 7]
  [20]
  [ 0]
  [22]
  [10]
  [ 7]
  [ 0]]

 [[17]
  [24]
  [ 7]
  [20]
  [ 0]
  [22]
  [10]
  [ 7]
  [ 0]
  [14]]

 [[24]
  [ 7]
  [20]
  [ 0]
  [22]
  [10]
  [ 7]
  [ 0]
  [14]
  [ 3]]

 [[ 7]
  [20]
  [ 0]
  [22]
  [10]
  [ 7]
  [ 0]
  [14]
  [ 3]
  [28]]

 [[20]
  [ 0]
  [22]
  [10]
  [ 7]
  [ 0]
  [14]
  [ 3]
  [28]
  [27]]

 [[ 0]
  [22]
  [10]
  [ 7]
  [ 0]
  [14]
  [ 3]
  [28]
  [27]
  [ 0]]

 [[22]
  [10]
  [ 7]
  [ 0]
  [14]
  [ 3]
  [28]
  [27]
  [ 0]
  [ 6]]

 [[10]
  [ 7]
  [ 0]
  [14]
  [ 3]
  [28]
  [27]
  [ 0]
  [ 6]
  [17]]

 [[ 7]
  [ 0]
  [14]
  [ 3]
  [28]
  [27]
  [ 0]
  [ 6]
  [17]
  [ 9]]

 [[ 0]
  [14]
  [ 3]
  [28]
  [27]
  [ 0]
  [ 6]
  [17]
  [ 9]
  [ 1]]] (of type <class 'tensorflow.python.framework.ops.EagerTensor'>)

In [34]:
# Generate text
def generate_text(seed, n_chars):
    result = seed
    for _ in range(n_chars):
        x = [char_to_int[c] for c in seed]
        x = pad_sequences([x], maxlen=seq_length)
        pred = model.predict(x, verbose=0)
        index = np.argmax(pred)
        result += chars[index]
        seed = seed[1:] + chars[index]
    return result

print(generate_text("The quick ", 50))

NameError: name 'np' is not defined